/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatBubble: typeof import('./src/components/ChatBubble.vue')['default']
    ChatCard: typeof import('./src/components/ChatCard.vue')['default']
    ChatInputPanel: typeof import('./src/components/ChatInputPanel.vue')['default']
    DChatCard: typeof import('./src/components/ChatCard.vue')['default']
    FriendChatContent: typeof import('./src/components/friend/FriendChatContent.vue')['default']
    FriendChatHead: typeof import('./src/components/friend/FriendChatHead.vue')['default']
    FriendChatInput: typeof import('./src/components/friend/FriendChatInput.vue')['default']
    FriendChatInputPanel: typeof import('./src/components/friend/FriendChatInputPanel.vue')['default']
    FriendListHead: typeof import('./src/components/friend/FriendListHead.vue')['default']
    FriendNotificationCard: typeof import('./src/components/notification/FriendNotificationCard.vue')['default']
    FriendSetting: typeof import('./src/components/friend/FriendSetting.vue')['default']
    GroupCard: typeof import('./src/components/GroupCard.vue')['default']
    GroupChatCard: typeof import('./src/components/GroupChatCard.vue')['default']
    GroupChatContent: typeof import('./src/components/group/GroupChatContent.vue')['default']
    GroupChatHead: typeof import('./src/components/group/GroupChatHead.vue')['default']
    GroupChatInputPanel: typeof import('./src/components/group/GroupChatInputPanel.vue')['default']
    GroupInputPanel: typeof import('./src/components/group/GroupInputPanel.vue')['default']
    GroupListHead: typeof import('./src/components/group/GroupListHead.vue')['default']
    GroupMemberList: typeof import('./src/components/group/GroupMemberList.vue')['default']
    GroupNotificationCard: typeof import('./src/components/notification/GroupNotificationCard.vue')['default']
    GroupSettings: typeof import('./src/components/group/GroupSettings.vue')['default']
    InputPanel: typeof import('./src/components/InputPanel.vue')['default']
    JoinGroupModal: typeof import('./src/components/JoinGroupModal.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NavSideBar: typeof import('./src/components/NavSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextButton: typeof import('./src/components/TextButton.vue')['default']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
