/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatBubble: typeof import('./src/components/ChatBubble/ChatBubble.vue')['default']
    ChatCard: typeof import('./src/components/ChatCard.vue')['default']
    ChatHead: typeof import('./src/components/ChatHead.vue')['default']
    ChatInputPanel: typeof import('./src/components/ChatInputPanel.vue')['default']
    ChatListContent: typeof import('./src/components/ChatList/ChatListContent.vue')['default']
    ChatListHead: typeof import('./src/components/ChatList/ChatListHead.vue')['default']
    CreateGroupModal: typeof import('./src/components/Modal/CreateGroupModal.vue')['default']
    DropdownBtn: typeof import('./src/components/ui/DropdownBtn.vue')['default']
    DropdownItem: typeof import('./src/components/ui/DropdownItem.vue')['default']
    EditProfileModal: typeof import('./src/components/Modal/EditProfileModal.vue')['default']
    FriendChatContent: typeof import('./src/components/friend/FriendChatContent.vue')['default']
    FriendNotificationCard: typeof import('./src/components/notification/FriendNotificationCard.vue')['default']
    FriendSetting: typeof import('./src/components/friend/FriendSetting.vue')['default']
    GroupChatContent: typeof import('./src/components/group/GroupChatContent.vue')['default']
    GroupJoinQuestionModal: typeof import('./src/components/Modal/GroupJoinQuestionModal.vue')['default']
    GroupMemberList: typeof import('./src/components/group/GroupMemberList.vue')['default']
    GroupNotificationCard: typeof import('./src/components/notification/GroupNotificationCard.vue')['default']
    GroupSettings: typeof import('./src/components/group/GroupSettings.vue')['default']
    IconBtn: typeof import('./src/components/ui/IconBtn.vue')['default']
    MobileSideBar: typeof import('./src/components/MobileSideBar.vue')['default']
    MobileSidebarBtn: typeof import('./src/components/MobileSidebarBtn.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NavSideBar: typeof import('./src/components/NavSideBar.vue')['default']
    NotificationCate: typeof import('./src/components/notification/NotificationCate.vue')['default']
    PlaceholderPage: typeof import('./src/components/PlaceholderPage.vue')['default']
    ProfileCard: typeof import('./src/components/ChatBubble/ProfileCard.vue')['default']
    RenameFriendModal: typeof import('./src/components/Modal/RenameFriendModal.vue')['default']
    RenameGroupModal: typeof import('./src/components/Modal/RenameGroupModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFriendModal: typeof import('./src/components/Modal/SearchFriendModal.vue')['default']
    SearchGroupModal: typeof import('./src/components/Modal/SearchGroupModal.vue')['default']
    TextButton: typeof import('./src/components/TextButton.vue')['default']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    TransferGroupModal: typeof import('./src/components/Modal/TransferGroupModal.vue')['default']
  }
}
